In [1]:
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa

In [2]:
import pandas as pd

In [ ]:
df = pd.read_parquet('202311.parquet')
# df.to_csv('out.csv', index=False)             # Exporting to CSV is easy
df.to_csv('202311.txt', index=False, sep=';') 

df = pd.read_parquet('202312.parquet')
# df.to_csv('out.csv', index=False)             # Exporting to CSV is easy
df.to_csv('202312.txt', index=False, sep=';')

In [8]:
import pandas as pd
# Load the CSV file
data = pd.read_parquet('labeled_data_05.parquet')

unique_locations = data['LOCATION'].nunique()
print(f'The number of unique locations is: {unique_locations}')

The number of unique locations is: 622
The first few unique locations are: [50254 52612 28539 10465 37822 67939 42876 41176  2880 28431]

In [2]:
# Read the Parquet file
df = pd.read_parquet('combined_labeled_data.parquet')
filtered_data = df[df['LOCATION'] == 25689]

In [3]:
filtered_data

,YYYYMMDD,LOCATION,RATECLASS_DESC,# of Chargers,R1,R2,R3,R4,R5,R6,...,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24
7130,20230101,25689,001: Residential: TOU,1.0,2.65,0.66,1.39,3.43,0.60,0.66,...,1.06,0.84,2.60,4.19,1.31,1.06,7.63,10.00,3.13,0.90
7131,20230102,25689,001: Residential: TOU,1.0,0.73,0.51,0.66,1.55,1.66,0.77,...,1.01,2.77,1.20,0.99,1.29,1.12,3.87,1.12,1.25,0.88
7132,20230103,25689,001: Residential: TOU,1.0,0.58,2.61,0.57,0.52,0.70,0.81,...,0.76,0.95,1.36,2.41,1.18,1.08,1.64,1.45,3.04,0.59
7133,20230104,25689,001: Residential: TOU,1.0,0.49,0.51,0.51,4.41,12.33,12.41,...,2.33,1.31,0.95,1.05,3.59,1.10,1.06,1.00,2.46,1.23
7134,20230105,25689,001: Residential: TOU,1.0,0.54,0.51,0.54,0.53,2.74,0.80,...,0.76,3.63,0.73,1.03,3.00,1.31,1.16,1.06,1.05,5.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210781,20231228,25689,001: Residential: TOU,1.0,0.51,0.47,0.52,0.52,0.48,2.80,...,1.01,2.95,1.06,1.11,1.11,1.05,3.18,1.15,1.21,0.83
210782,20231229,25689,001: Residential: TOU,1.0,0.51,0.54,2.63,0.53,0.54,0.70,...,1.74,4.22,1.12,1.60,1.13,1.20,1.74,4.07,1.29,0.57
210783,20231230,25689,001: Residential: TOU,1.0,0.51,0.49,3.99,12.10,12.03,12.03,...,2.27,0.75,0.85,1.00,2.96,0.83,0.81,0.86,1.02,2.73
210784,20231231,25689,001: Residential: TOU,1.0,0.47,0.51,0.47,0.51,2.61,0.51,...,1.61,3.04,1.20,1.10,1.19,1.90,2.29,1.07,1.17,1.21
210785,20231204,25689,001: Residential: TOU,1.0,2.54,0.51,0.56,0.55,0.52,10.42,...,0.62,1.96,1.35,0.86,0.87,0.85,1.61,2.41,0.76,0.51

In [4]:
filtered_data.to_csv('25689.csv', index=False)

In [57]:
# change column name
df = pd.read_parquet('202312.parquet')
print("Original columns:", df.columns)
df = df.rename(columns={'Chargers': '# of Chargers'})
print("Updated columns:", df.columns)
df.to_parquet('202312.parquet')

Original columns: Index(['YYYYMMDD', 'LOCATION', 'RATECLASS_DESC', 'Chargers', 'R1', 'R2', 'R3',
       'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13', 'R14',
       'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21', 'R22', 'R23', 'R24'],
      dtype='object')
Updated columns: Index(['YYYYMMDD', 'LOCATION', 'RATECLASS_DESC', '# of Chargers', 'R1', 'R2',
       'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13',
       'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21', 'R22', 'R23',
       'R24'],
      dtype='object')

In [89]:
# Extract labeled data
data_frames = []
file_name = '202312.parquet'
data_frames.append(pd.read_parquet(file_name))

data = pd.concat(data_frames, ignore_index=True)


irrelevant_categories = ['020: Street Lighting: HOEP', '018: Unmetered Scattered Load', '021: Street Lighting: Tiered']
data = data[~data['RATECLASS_DESC'].isin(irrelevant_categories)]
data['# of Chargers'] = pd.to_numeric(data['# of Chargers'], errors='coerce')


labeled_data = data.dropna(subset=['# of Chargers'])
unlabeled_data = data[data['# of Chargers'].isna()].drop(columns=['# of Chargers'])


output_file_labeled = 'labeled_data_12.parquet'
labeled_data.to_parquet(output_file_labeled, engine='pyarrow')

In [106]:
data = pd.read_parquet('combined_labeled_data.parquet')
#data = pd.read_parquet('labeled_data_11.parquet')
#data = pd.read_parquet('202308.parquet')

In [107]:
data

,YYYYMMDD,LOCATION,RATECLASS_DESC,# of Chargers,R1,R2,R3,R4,R5,R6,...,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24
0,20230101,23,001: Residential: TOU,1.0,1.06,0.83,0.79,0.72,0.60,0.63,...,1.43,1.15,0.88,0.86,1.27,1.43,1.67,1.74,1.44,1.07
1,20230102,23,001: Residential: TOU,1.0,0.88,1.05,0.54,0.55,0.49,0.51,...,1.57,2.47,2.68,1.57,1.94,1.25,1.25,1.26,1.19,1.13
2,20230131,23,001: Residential: TOU,1.0,1.31,1.01,0.93,0.75,0.81,1.05,...,0.79,1.01,1.02,1.19,1.95,2.17,1.90,2.03,1.05,0.89
3,20230103,23,001: Residential: TOU,1.0,0.84,0.75,0.54,0.55,0.52,0.54,...,0.74,0.92,0.73,0.71,0.89,0.83,1.24,1.51,1.19,0.84
4,20230104,23,001: Residential: TOU,1.0,0.79,0.81,0.66,0.64,0.62,0.86,...,0.65,0.89,1.09,1.12,1.10,1.09,0.99,1.05,1.15,0.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227647,20231227,4967,001: Residential: TOU,1.0,1.58,0.69,0.72,1.49,0.81,1.93,...,0.89,1.57,0.79,1.87,0.82,1.75,0.81,0.86,1.54,0.74
227648,20231228,4967,001: Residential: TOU,1.0,1.46,0.88,0.64,1.59,0.72,1.96,...,1.66,0.85,0.68,1.80,0.73,1.91,1.65,2.01,0.69,1.59
227649,20231229,4967,001: Residential: TOU,1.0,0.71,1.51,0.74,0.67,1.69,1.06,...,1.56,0.82,1.67,0.87,1.90,3.18,2.08,1.25,1.57,0.88
227650,20231230,4967,001: Residential: TOU,1.0,0.71,1.61,0.79,1.39,1.33,1.66,...,1.84,0.91,1.88,1.17,1.52,6.17,8.82,9.93,4.72,1.69
227651,20231231,4967,001: Residential: TOU,1.0,0.77,1.52,0.69,1.59,0.93,2.04,...,1.70,1.05,1.87,0.93,1.99,4.94,9.74,8.78,7.14,0.78

In [ ]:
#combine data
combined_data_frames = []
for month in range(1, 13):
    file_name = f'2023{month:02d}.parquet'
    combined_data_frames.append(pd.read_parquet(file_name))

combined_data = pd.concat(combined_data_frames, ignore_index=True)

# Step 2: Save the combined DataFrame to a new Parquet file
output_file_combined = 'combined_data.parquet'
combined_data.to_parquet(output_file_combined, engine='pyarrow')

In [ ]:
# xlsx to prequet
file_path = '202309.xlsx'
xls = pd.ExcelFile(file_path)
sheet_names = xls.sheet_names
data_df = pd.read_excel(file_path, sheet_name=sheet_names[0])
column_names = data_df.columns.tolist()
dfs = [data_df]
for sheet_name in sheet_names[1:]:  # Skip the first sheet since it's already read
    df = pd.read_excel(file_path, sheet_name=sheet_name, header=None, names=column_names)
    dfs.append(df)
combined_df = pd.concat(dfs, ignore_index=True)
combined_df.to_parquet('202309.parquet')

In [4]:
data = pd.read_parquet('202307.parquet')

In [5]:
data

,YYYYMMDD,LOCATION,RATECLASS_DESC,Chargers,R1,R2,R3,R4,R5,R6,...,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24
0,20230601,1,020: Street Lighting: HOEP,NaN,1118.16,1118.16,1118.16,1118.16,1043.62,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,969.07,1118.16,1118.16,1118.16
1,20230602,1,020: Street Lighting: HOEP,NaN,1118.16,1118.16,1118.16,1118.16,1043.62,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,950.44,1118.16,1118.16,1118.16
2,20230603,1,020: Street Lighting: HOEP,NaN,1118.16,1118.16,1118.16,1118.16,1043.62,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,931.80,1118.16,1118.16,1118.16
3,20230604,1,020: Street Lighting: HOEP,NaN,1118.16,1118.16,1118.16,1118.16,1024.98,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,931.80,1118.16,1118.16,1118.16
4,20230605,1,020: Street Lighting: HOEP,NaN,1118.16,1118.16,1118.16,1118.16,1024.98,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,913.17,1118.16,1118.16,1118.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072339,20230626,52116,001: Residential: TOU,NaN,2.30,2.69,2.75,2.20,2.84,3.03,...,3.30,4.81,4.43,4.27,4.93,6.66,5.36,4.28,3.45,3.28
2072340,20230627,52116,001: Residential: TOU,NaN,2.15,2.79,2.16,2.16,2.82,2.13,...,5.46,2.45,2.66,4.79,5.84,5.57,4.49,4.72,3.32,3.55
2072341,20230628,52116,001: Residential: TOU,NaN,1.97,1.98,1.94,1.96,1.91,1.97,...,4.37,4.74,7.04,5.28,4.66,3.75,4.63,5.05,3.54,2.23
2072342,20230629,52116,001: Residential: TOU,NaN,2.16,2.06,2.18,2.18,2.13,2.20,...,5.04,4.56,5.06,5.46,4.50,6.45,6.01,5.26,3.32,2.98
2072343,20230630,52116,001: Residential: TOU,NaN,2.00,2.62,2.03,2.70,1.99,2.75,...,5.49,6.18,6.89,5.20,4.22,7.76,7.26,6.10,4.42,3.72